default:
  app:
    name: Jukeberry
    version: 1.0.1

  broker:
    mqtt:
      url: tcp://mr1nljqp0y1g2d.messaging.solace.cloud:21126
      topics: ["card/presented","stop/pushed/#"]
      qos:
      protocol: mqtt
      retain:
      subscribe: true
      config: { username: "solace-cloud-client", password: "7ide7v7illr1fs4bsio3ls26f0"}

development:

test:

staging:

production:

