default:
  app:
    name: Jukeberry
    version: 1.0.0

  broker:
    mqtt:
      url: mqtt://localhost
      topics: ["card/presented","stop/pushed/#"]
      qos:
      protocol: mqtt
      retain:
      subscribe: true

development:

test:

staging:

production:
